--  Assignment 3

--  Q1.
  SELECT CHR(97),CHR(74) AS CHR FROM DUAL;

--  Q2.
  SELECT CONCAT('HELLO',' WORLD') AS CONCATENATION FROM DUAL;

--  Q3.
  SELECT INSTR('SUKHMAN','U') AS INSTRING FROM DUAL;

--  Q4.
  SELECT LENGTH('SUKHMANPREET SINGH') AS LENGTH FROKM DUAL;

--  Q5.
  SELECT LPAD('SUKHMAN',12,'*') AS LPAD FROM DUAL;

--  Q6.
  SELECT LTRIM('    SUKHMAN','    ') AS LTRIM FROM DUAL;

--  Q7.
  SELECT RPAD('SUKHMAN',12'*') AS RPAD FROM DUAL;

--  Q8.
  SELECT RTRIM('SUKHMAN    ','    ') AS RTRIM FROM DUAL;

--  Q9.
  SELECT REPLACE('SUKHMANPREET SINGH','SINGH','KAUR') AS REPLACE FROM DUAL;

--  Q10.
  SELECT SUBSTR('SUKHMANPREET',3,10) AS SUBSTR FROM DUAL;

--  Q11.
  SELECT INITCAP('sukhman') AS INITCAP FROM DUAL;

--  Q12.
  SELECT LOWER('SUKHMAN') AS LOWER FROM DUAL;

--  Q13.
  SELECT UPPER('sukhman') AS UPPER FROM DUAL;

--  Q14.
  SELECT TRANSLATE('SUKHMANPREET','E','*') AS TRANSLATE FROM DUAL;

--  Q15.
  SELECT ABS(-43536) AS ABS FROM DUAL;

--  Q16.
  SELECT CEIL(47.2) AS CEIL FROM DUAL;

-- Q17.  (COS TAKES VALUES IN RADIAN)
  SELECT COS(0) AS COS FROM DUAL;

--  Q18.  (RETURNS e^x)
  SELECT EXP(5) AS EXP FROM DUAL;

--  Q19.
  SELECT FLOOR(57468.8) AS FLOOR FROM DUAL;

--  Q20.
  SELECT MOD(23,8) AS MOD FROM DUAL;

--  Q21.
  SELECT POWER(2,5) AS POWER FROM DUAL;

--  Q22.
  SELECT ROUND(435.8934,2) AS ROUNDOFF FROM DUAL;

--  Q23.
  SELECT SIGN(-43),SIGN(6453) AS SIGN FROM DUAL;

--  Q24.
  SELECT SQRT(81) AS SQRT FROM DUAL;

--  Q25.  (TRUNCATE FUNCTION JUST CUTS OFF THE DESIRED DIGITS WITHOUT ROUNDING OFF JUST FOR THE SAKE OF PRECISION)
  SELECT TRUNC(374.564),TRUNC(3465.863,-2),TRUNC(365.889,2) AS TRUNC FROM DUAL;

--  Q26.
  SELECT SYSDATE AS SYSTEM_DATE FROM DUAL;

--  Q27.
  SELECT ADD_MONTHS(SYSDATE,12) AS ADDING_MONTHS FROM DUAL;

--  Q28.
  SELECT LAST_DAY(SYSDATE) AS LAST_DAY_OF_MONTH FROM DUAL;

--  Q29.
  SELECT MONTHS_BETWEEN('13-OCT-25',SYSDATE) AS MONTHS_LEFT FROM DUAL;

--  Q30.  (RETURNS THE NEXT DATE OF THE THE COMING WEEK ON THE SAME DAY)
  SELECT NEXT_DAY(SYSDATE,'SATURDAY') AS NEXT_DAY FROM DUAL;

--  Q31.
  SELECT GREATEST(23,4,12) AS GREATEST FROM DUAL;

--  Q32.
  SELECT LEAST('XYZ','ABC','EFG') AS LEAST FROM DUAL;

--  Q33.
  SELECT TO_CHAR(SYSTIMESTAMP AT TIME ZONE 'Asia/Kolkata', 'HH24:MI:SS') AS LOCAL_TIME FROM DUAL;

--  Q34.
  CREATE TABLE EMP(EMPID INT,NAME VARCHAR(20),SALARY FLOAT,COMMISSION FLOAT,DOJ DATE);
  INSERT INTO EMP VALUES(101,'SUKHMAN',50000000,371532.32,'13-JAN-85');
  INSERT INTO EMP VALUES(102,'HARITH',1000000,71532.32,'31-MAR-85');
  INSERT INTO EMP VALUES(103,'DAKSH',7400000,31532.32,'23-SEP-24');
  INSERT INTO EMP VALUES(104,'ARSHDEEP',5000000,78532.32,'20-OCT-25');
  INSERT INTO EMP VALUES(105,'ESHAAN',10000000,103215.32,'1-APR-25');
  SELECT * FROM EMP;
  SELECT (SALARY+COMMISSION) AS TOTAL_SAL FROM EMP;

--  Q35.
  ALTER TABLE EMP ADD HIREDATE DATE;
  UPDATE EMP SET HIREDATE = DOJ;
  SELECT * FROM EMP;

--  Q36.
  SELECT NAME FROM EMP WHERE TO_CHAR(DOJ,'YYYY') = '1985';

--  Q37.
  SELECT NAME FROM EMP WHERE TO_CHAR(DOJ,'YYYY') = TO_CHAR(SYSDATE,'YYYY');




