--  Assignment 2

  CREATE TABLE EMP(EMPNO INT,ENAME VARCHAR(20),JOB VARCHAR(20),SALARY FLOAT,COMMISSION FLOAT,DEPTNO INT);
    
  INSERT INTO EMP VALUES(1, 'JOHN', 'CLERK', 2500, NULL, 10);
  INSERT INTO EMP VALUES(2, 'RAJ', 'SALESPERSON', 3000, 500, 20);
  INSERT INTO EMP VALUES(3, 'JANE', 'MANAGER', 4000, NULL, 30);
  INSERT INTO EMP VALUES(4, 'CHRIS', 'CLERK', 1500, NULL, 10);
  INSERT INTO EMP VALUES(5, 'ANNA', 'SALESPERSON', 3500, 700, 30);

--  Q1.
  SELECT EMPNO,ENAME FROM EMP WHERE DEPTNO = 10;

--  Q2.
  SELECT ENAME FROM EMP WHERE JOB = 'CLERK' AND SALARY > 2000;

--  Q3.
  SELECT ENAME,JOB FROM EMP WHERE JOB IN ('SALESPERSON','CLERK');

--  Q4.
  SELECT * FROM EMP WHERE SALARY BETWEEN 2000 AND 3000;

--  Q5.
  SELECT * FROM EMP WHERE DEPTNO IN (10,20,30);

--  Q6.
  SELECT ENAME FROM EMP WHERE COMMISSION IS NULL;

--  Q7.
  SELECT DEPTNO,SALARY FROM EMP ORDER BY DEPTNO ASC,SALARY DESC;

--  Q8.
  SELECT ENAME FROM EMP WHERE ENAME LIKE '%A%A%' OR ENAME LIKE '%a%a%';

--  Q9.
  SELECT ENAME FROM EMP WHERE ENAME LIKE '_B%' OR ENAME LIKE '_b%';

--  Q10.
  SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' OR ENAME LIKE '%A' OR ENAME LIKE 'a%' OR ENAME LIKE '%a';

--  Q11.
  SELECT MAX(SALARY),MIN(SALARY),AVG(SALARY) FROM EMP WHERE DEPTNO = 10;

--  Q12.
  SELECT COUNT(*) AS TOTAL_EMP FROM EMP WHERE DEPTNO = 20;

--  Q13.
  SELECT SUM(SALARY) AS TOTAL_SAL FROM EMP WHERE JOB = 'CLERK';

--  Q14.
  SELECT SYSDATE AS SYSTEM_DATE FROM DUAL;

--  Q15.
  SELECT (12*12)/13 FROM DUAL;

--  Q16.
  






