-- Assignment 4


-- Q1.
  SELECT SYSDATE FROM DUAL;

-- Q2.
  SELECT TO_CHAR(SYSDATE,'DAY') AS DAY FROM DUAL;

-- Q3.
  SELECT TO_CHAR(SYSDATE,'MONTH,YYYYSP') FROM DUAL;

-- Q4.
  SELECT TO_CHAR(SYSDATE,'DDSP-MMSP-YYYYSP') FROM DUAL;

-- Q5.
  SELECT TO_CHAR(SYSDATE,'AM') AS AM_PM FROM DUAL;

-- Q6.
  SELECT NEXT_DAY(SYSDATE,'FRIDAY') AS NEXT_FRIDAY FROM DUAL;

-- Q7.
  SELECT ROUND(SYSDATE,'MONTH') AS ROUNDED_MONTH FROM DUAL;

-- Q8.
  SELECT TRUNC(SYSDATE,'MONTH') AS TRUNCATED_MONTH FROM DUAL;

-- Q9.
  SELECT ROUND(SYSDATE,'YEAR') AS ROUNDED_YEAR FROM DUAL;

-- Q10.
  SELECT TRUNC(SYSDATE,'YEAR') AS TRUNCATED_YEAR FROM DUAL;


